### ISSUE TITLE
实例化全局单例logger的时候会触发config系统初始化从而无法再次加载profile变量

### ISSUE THREAD

**Issue by carolove** [cuigh/auxo#2]
```go
package main

import (
	"fmt"

	"github.com/cuigh/auxo/app/flag"
	"github.com/cuigh/auxo/config"
	"github.com/cuigh/auxo/log"
	"github.com/cuigh/auxo/app"
)

var logxxx = log.Get("log")

func main() {
	app.Name = "test6"
	app.Version = "0.0.1"
	app.Desc = "golang"
	app.Action = func(ctx *app.Context) {
		fmt.Println("web.mode is", config.GetString("web.mode"))
	}
	app.Flags.Register(flag.All)

	app.Start()
}
```

##3#################################
step:
chendan@chendan-TM1604:~/lesson6$ ./lesson6
     ___      __    __  ___   ___   ______
    /   \    |  |  |  | \  \ /  /  /  __  \
   /  ^  \   |  |  |  |  \  V  /  |  |  |  |
  /  /_\  \  |  |  |  |   >   <   |  |  |  |
 /  _____  \ |  '--'  |  /  .  \  |  '--'  |
/__/     \__\ \______/  /__/ \__\  \______/     VERSION 0.6.4

**web.mode is dev@dev**

step:
chendan@chendan-TM1604:~/lesson6$ ./lesson6 -p prd
     ___      __    __  ___   ___   ______
    /   \    |  |  |  | \  \ /  /  /  __  \
   /  ^  \   |  |  |  |  \  V  /  |  |  |  |
  /  /_\  \  |  |  |  |   >   <   |  |  |  |
 /  _____  \ |  '--'  |  /  .  \  |  '--'  |
/__/     \__\ \______/  /__/ \__\  \______/     VERSION 0.6.4

**web.mode is dev@dev**

**Comment by cuigh** [comment]
这是设计成这样的，为了简化使用，部分组件如日志会自动初始化配置，你可以调整下 Logger 对象初始化的顺序

```go
var logger log.Logger

func main() {
    app.Name = "test6"
    app.Action = func(ctx *app.Context) {
        logger = log.Get("log")  // 在 app.Start 执行后初始化
        fmt.Println("web.mode is", config.GetString("web.mode"))
    }
    app.Flags.Register(flag.All)
    app.Start()
}
```

**Comment by carolove** [comment]
是的我在实际中的确是调整以后绕过去了，这个在readme中最好写一下，我在用的时候不知道有这么一个逻辑，发现总是加载不上来其他环境的参数

**Comment by cuigh** [comment]
嗯，后面文档中会补充这一块的问题，不过尽量不使用全局变量是一个好习惯，除非是那种明显没有状态的对象。
